###
GET https://dev-sg.appcubecloud.com/magno/gallery/asset/plugin/widget
Access-Token: 

###
GET https://dev-sg.appcubecloud.com/magno/gallery/asset/widget/{{$dotenv VITE_WIDGET_ID}}
Access-Token: 

###
POST https://dev-sg.appcubecloud.com/baas/auth/v1.0/oauth2/token?grant_type=client_credentials&client_id={{$dotenv VITE_CLIENT_ID}}&client_secret={{$dotenv VITE_CLIENT_SECRET}}
