###
POST https://dev-sg.appcubecloud.com/magno/gallery/asset/widget
Access-Token: 
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7LAsFjEt1cITGDye

------WebKitFormBoundary7LAsFjEt1cITGDye
Content-Disposition: form-data; name="id"

{{$dotenv VITE_WIDGET_ID}}
------WebKitFormBoundary7LAsFjEt1cITGDye
Content-Disposition: form-data; name="identifier"

{widgetIdentifier}
------WebKitFormBoundary7LAsFjEt1cITGDye
Content-Disposition: form-data; name="name"

{"zh_CN":"{组件名}","en_US":"{widgetName}"}
------WebKitFormBoundary7LAsFjEt1cITGDye
Content-Disposition: form-data; name="description"

{"zh_CN":"{组件描述}","en_US":"{widgetDescription}"}
------WebKitFormBoundary7LAsFjEt1cITGDye
Content-Disposition: form-data; name="file"; filename="{zipFile}"
Content-Type: application/x-zip-compressed

< {pathToZipFile}
------WebKitFormBoundary7LAsFjEt1cITGDye
Content-Disposition: form-data; name="category"

16f519d485e-328fa286-893e-43ea-830c-460a2ef178e5
------WebKitFormBoundary7LAsFjEt1cITGDye
Content-Disposition: form-data; name="industry"

16c519d44af-361631af-9929-4822-a271-5dc702c81749
------WebKitFormBoundary7LAsFjEt1cITGDye
Content-Disposition: form-data; name="scenario"

00000000000000000001
------WebKitFormBoundary7LAsFjEt1cITGDye--